name: Push Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Run every hour

# Restrict permissions to the minimum required
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c

      - name: Install dependencies
        run: dart pub get

      - name: Run app / Push metrics
        env:
          GRAFANA_LOKI_USERNAME: ${{ secrets.GRAFANA_LOKI_USERNAME }}
          GRAFANA_LOKI_TOKEN: ${{ secrets.GRAFANA_LOKI_TOKEN }}
          GRAFANA_LOKI_URL: ${{ secrets.GRAFANA_LOKI_URL }}
          GRAFANA_PROM_USERNAME: ${{ secrets.GRAFANA_PROM_USERNAME }}
          GRAFANA_PROM_TOKEN: ${{ secrets.GRAFANA_PROM_TOKEN }}
          GRAFANA_PROM_REMOTE_WRITE_URL: ${{ secrets.GRAFANA_PROM_REMOTE_WRITE_URL }}
          GARDENA_CLIENT_ID: ${{ secrets.GARDENA_CLIENT_ID }}
          GARDENA_CLIENT_SECRET: ${{ secrets.GARDENA_CLIENT_SECRET }}
        run: dart run
